config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  post '/graphql', to: 'graphql#execute'

  devise_for :users, only: %i[sessions omniauth_callbacks], controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/send_login_email', controller: 'users/sessions', action: 'send_login_email', as: 'user_send_login_email'
    post 'users/send_reset_password_email', controller: 'users/sessions', action: 'send_reset_password_email', as: 'user_send_reset_password_email'
    get 'users/token', controller: 'users/sessions', action: 'token', as: 'user_token'
    get 'users/reset_password', controller: 'users/sessions', action: 'reset_password', as: 'reset_password'
    post 'users/update_password', controller: 'users/sessions', action: 'update_password', as: 'update_password'

    if Rails.env.development?
      get 'users/auth/developer', controller: 'users/omniauth_callbacks', action: 'passthru', as: 'user_developer_omniauth_authorize'
      post 'users/auth/developer/callback', controller: 'users/omniauth_callbacks', action: 'developer'
    end
  end

  get 'users/delete_account', controller: 'users', action: 'delete_account', as: 'delete_account'

  post 'users/email_bounce', controller: 'users/postmark_webhook', action: 'email_bounce'

  authenticate :user, ->(u) { AdminUser.where(email: u.email).present? } do
    mount Delayed::Web::Engine, at: '/jobs'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resource :applicants, only: [] do
    get '/:token', action: 'enroll' # TODO: Legacy route - remove after a few weeks.
    get '/:token/enroll', action: 'enroll', as: 'enroll'
  end

  resources :notifications, only: %i[show]

  resource :school, only: %i[show update] do
    get 'customize'
    get 'admins'
    post 'images'
  end

  namespace :school, module: 'schools' do
    resources :faculty, only: %i[create update destroy], as: 'coaches', path: 'coaches' do
      collection do
        get '/', action: 'school_index'
      end
    end

    resources :targets, only: [] do
      resource :content_block, only: %i[create]
    end

    resources :courses, only: %i[index show new] do
      member do
        get 'details'
        get 'images', action: :details
        get 'actions', action: :details
        get 'curriculum'
        get 'exports'
        get 'authors'
        get 'certificates'
        post 'certificates', action: 'create_certificate'
        post 'bulk_import_students'
        get 'evaluation_criteria'
        post 'attach_images'
      end

      resources :authors, only: %w[show new]

      resources :targets, only: [] do
        member do
          get 'content'
          get 'details'
          get 'versions'
        end
      end

      resources :levels, only: %i[create]

      resources :faculty, as: 'coaches', path: 'coaches', only: [] do
        collection do
          get '/', action: 'course_index'
        end
      end

      post 'mark_teams_active'
      get 'students'
      get 'inactive_students'
      post 'delete_coach_enrollment'
      post 'update_coach_enrollments'
    end

    resources :founders, as: 'students', path: 'students', except: %i[index] do
      collection do
        post 'team_up'
      end
    end

    resources :levels, only: %i[update] do
      resources :target_groups, only: %i[create]
    end

    resources :target_groups, only: %i[update]

    resources :communities, only: %i[index]
  end

  resources :communities, only: %i[show] do
    member do
      get 'new_topic'
      get ':name', action: 'show'
    end
  end

  get 'topics/:id(/:title)', controller: 'topics', action: 'show', as: 'topic'

  get 'posts/:id/versions', controller: 'posts', action: 'versions', as: 'post_version'

  get 'dashboard', controller: 'users', action: 'dashboard', as: 'dashboard'

  resource :user, only: %i[edit] do
    post 'upload_avatar'
  end

  resources :timeline_event_files, only: %i[create] do
    member do
      get 'download'
    end
  end

  resources :faculty, only: %i[] do
    collection do
      get 'filter/:active_tab', to: 'faculty#index'
      get 'weekly_slots/:token', to: 'faculty#weekly_slots', as: 'weekly_slots'
      post 'save_weekly_slots/:token', to: 'faculty#save_weekly_slots', as: 'save_weekly_slots'
      delete 'weekly_slots/:token', to: 'faculty#mark_unavailable', as: 'mark_unavailable'
      get 'slots_saved/:token', to: 'faculty#slots_saved', as: 'slots_saved'
    end
  end

  scope 'coaches', controller: 'faculty' do
    get '/', action: 'index', as: 'coaches_index'
    get '/:id(/:slug)', action: 'show', as: 'coach'
    get '/filter/:active_tab', action: 'index'
  end

  scope 'connect_request', controller: 'connect_request', as: 'connect_request' do
    get ':id/feedback/from_team/:token', action: 'feedback_from_team', as: 'feedback_from_team'
    get ':id/feedback/from_faculty/:token', action: 'feedback_from_faculty', as: 'feedback_from_faculty'
    get ':id/join_session(/:token)', action: 'join_session', as: 'join_session'
    patch ':id/feedback/comment/:token', action: 'comment_submit', as: 'comment_submit'
  end

  # Founder show
  scope 'students', controller: 'founders' do
    get '/:id/report', action: 'report', as: 'student_report'
  end

  get 'styleguide', to: 'home#styleguide', constraints: DevelopmentConstraint.new

  get 'manifest', to: 'home#manifest'
  get 'offline', to: 'home#offline'
  root 'home#index'

  # TODO: Remove this backwards-compatibility path after Jan 2021.
  get 'agreements/terms-of-use', to: redirect('/agreements/terms-and-conditions')

  get 'agreements/:agreement_type', as: 'agreement', controller: 'home', action: 'agreement'

  resources :targets, only: %i[show] do
    member do
      get 'details_v2'
      get ':slug', action: 'show'
    end
  end

  resources :timeline_events, only: %i[show], path: 'submissions' do
    member do
      get 'review', action: 'review'
    end
  end

  resources :courses, only: %i[show] do
    member do
      get 'review', action: 'review'
      get 'students', action: 'students'
      get 'leaderboard', action: 'leaderboard'
      get 'curriculum', action: 'curriculum'
      get 'report', action: 'report'
      get 'apply', action: 'apply'
      get '/(:name)', action: 'show'
    end
  end

  resources :markdown_attachments, only: %i[create] do
    member do
      get '/:token', action: 'download', as: 'download'
    end
  end

  get '/c/:serial_number', to: 'issued_certificates#verify', as: :issued_certificate
  get '/help/:document', to: 'help#show'
  get '/oauth/:provider', to: 'home#oauth', as: 'oauth', constraints: SsoConstraint.new
  get '/oauth_error', to: 'home#oauth_error', as: 'oauth_error'

  # Allow developers to simulate the error pages.
  get '/errors/:error_type', to: 'errors#simulate', constraints: DevelopmentConstraint.new

  get '/service-worker.js', to: 'home#service_worker'
  get '/favicon.ico', to: 'home#favicon'
end

app/controllers/schools/authors_controller.rb
module Schools
  class AuthorsController < SchoolsController
    # GET /school/courses/:course_id/authors/new
    def new
      @course = current_school.courses.find(params[:course_id])
      authorize(@course.course_authors.new, policy_class: Schools::CourseAuthorPolicy)
      render 'schools/courses/authors'
    end

    # GET /school/courses/:course_id/authors/:id
    def show
      @course = current_school.courses.find(params[:course_id])
      authorize(@course.course_authors.find(params[:id]), policy_class: Schools::CourseAuthorPolicy)
      render 'schools/courses/authors'
    end
  end
end

app/controllers/schools/communities_controller.rb
module Schools
  class CommunitiesController < SchoolsController
    def index
      @school = authorize(current_school, policy_class: Schools::CommunityPolicy)
      render layout: 'school'
    end
  end
end

app/controllers/schools/content_blocks_controller.rb
module Schools
  class ContentBlocksController < SchoolsController
    include CamelizeKeys
    include StringifyIds

    # POST /school/targets/:target_id/content_block
    def create
      target = Target.find(params[:target_id])

      # Let's authorize against the level, since that's the resource we have with a matching action in the policy.
      authorize(target.level, policy_class: Schools::LevelPolicy)

      form = ::Schools::Targets::CreateContentBlockForm.new(ContentBlock.new)

      if form.validate(params)
        render json: camelize_keys(stringify_ids(form.save.merge(error: nil)))
      else
        render json: { error: form.errors.full_messages.join(', ') }
      end
    end
  end
end

app/controllers/schools/courses_controller.rb
module Schools
  class CoursesController < SchoolsController
    include CamelizeKeys
    include StringifyIds

    layout 'school'

    # GET /school/courses
    def index
      authorize(current_school, policy_class: Schools::CoursePolicy)
    end

    # GET /school/course/new
    def new
      index
      render 'index'
    end

    # GET /school/course/id/
    def show
      @course = authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
      redirect_to details_school_course_path
    end

    # GET /school/course/id/details
    def details
      @course = authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
      render 'index'
    end

    # POST /courses/id/attach_images
    def attach_images
      course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
      @form = Schools::Courses::UpdateImagesForm.new(course)

      if @form.validate(params)
        @form.save
        render json: {
          thumbnail_url: course.thumbnail_url,
          cover_url: course.cover_url,
          error: nil
        }
      else
        render json: {
          thumbnail_url: nil,
          cover_url: nil,
          error: @form.errors.full_messages.join(', ')
        }
      end
    end

    # GET /courses/:id/curriculum
    def curriculum
      course =
        scope
          .where(id: params[:id])
          .includes(:evaluation_criteria, :levels, :target_groups, :targets)
          .first
      @course = authorize(course, policy_class: Schools::CoursePolicy)
    end

    # POST /school/courses/:course_id/delete_coach_enrollment
    def delete_coach_enrollment
      coach = current_school.faculty.find(params[:coach_id])
      course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )

      ::Courses::UnassignReviewerService.new(course).unassign(coach)

      render json: { coach_id: coach.id.to_s, error: nil }
    end

    def update_coach_enrollments
      course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )
      coaches =
        current_school.faculty.where(id: params[:coach_ids]).includes(:school)

      coaches.each do |coach|
        ::Courses::AssignReviewerService.new(course, notify: true).assign(coach)
      end

      course_coaches =
        coaches.map do |coach|
          {
            id: coach.id.to_s,
            name: coach.name,
            title: coach.title,
            email: coach.email,
            avatarUrl: coach.user.avatar_url(variant: :thumb)
          }
        end

      render json: { course_coaches: course_coaches, error: nil }
    end

    # GET /school/courses/:course_id/students
    def students
      @course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )
    end

    def inactive_students
      @course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )

      inactive_teams =
        if params[:search].present?
          ::Courses::InactiveTeamsSearchService
            .new(@course)
            .find_teams(params[:search].to_s)
        else
          Startup.joins(:course).inactive.where(courses: { id: @course }).to_a
        end

      @teams =
        Kaminari.paginate_array(inactive_teams).page(params[:page]).per(20)
    end

    # POST /school/courses/:course_id/mark_teams_active?team_ids[]=
    def mark_teams_active
      course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )

      Startup.transaction do
        course
          .startups
          .where(id: params[:team_ids])
          .each do |startup|
          startup.update!(access_ends_at: nil, dropped_out_at: nil)
        end

        render json: {
          message: 'Teams marked active successfully!',
          error: nil
        }
      end
    end

    # GET /school/courses/:id/exports
    def exports
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    # GET /school/courses/:id/authors
    def authors
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    # GET /school/courses/:id/certificates
    def certificates
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    # POST /school/courses/:id/certificates
    def create_certificate
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)

      form = ::Courses::CreateCertificateForm.new(@course)

      props =
        if form.validate(params)
          scope = Certificate.where(id: form.save.id)
          ActiveRecord::Precounter.new(scope).precount(:issued_certificates)

          {
            error: nil,
            certificate:
              Schools::Courses::CertificatesPresenter.certificate_details(
                scope.first
              )
          }
        else
          { error: form.errors.full_messages.join(', ') }
        end

      render json: camelize_keys(stringify_ids(props))
    end


    # POST /school/courses/:id/bulk_import_students
    def bulk_import_students
      @course = authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)

      form = ::Courses::BulkImportStudentsForm.new(@course)
      form.current_user = current_user

      props = if form.validate(params)
        form.save
        {
          success: true,
        }
      else
        { error: form.errors.full_messages.join(", ") }
      end

      render json: camelize_keys(stringify_ids(props))
    end

    # GET /school/courses/:id/evaluation_criteria
    def evaluation_criteria
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    private

    def scope
      @scope ||=
        policy_scope(Course, policy_scope_class: Schools::CoursePolicy::Scope)
    end
  end
end

app/controllers/schools/faculty_controller.rb
module Schools
  class FacultyController < SchoolsController
    # GET /school/coaches
    def school_index
      @school = authorize(current_school, policy_class: Schools::FacultyPolicy)
    end

    # POST /school/coaches
    def create
      @school = authorize(current_school, policy_class: Schools::FacultyPolicy)
      @form = Schools::Coaches::CreateForm.new(Faculty.new)

      if @form.validate(params[:faculty].merge(school_id: current_school.id))
        faculty = @form.save
        render json: { id: faculty.id, image_url: faculty.user.image_or_avatar_url, error: nil }
      else
        render json: { error: @form.errors.full_messages.join(', ') }
      end
    end

    def update
      @form = Schools::Coaches::UpdateForm.new(faculty)

      if @form.validate(params[:faculty].merge(school_id: current_school.id))
        faculty = @form.save
        render json: { id: faculty.id, image_url: faculty.user.image_or_avatar_url, error: nil }
      else
        render json: { error: @form.errors.full_messages.join(', ') }
      end
    end

    def course_index
      @course = policy_scope(Course, policy_scope_class: Schools::CoursePolicy::Scope).find(params[:course_id])
      authorize(current_school, policy_class: Schools::FacultyPolicy)
    end

    def faculty
      @faculty = authorize(Faculty.find(params[:id]), policy_class: Schools::FacultyPolicy)
    end
  end
end

app/controllers/schools/founders_controller.rb
module Schools
  class FoundersController < SchoolsController
    # POST /school/students/team_up?founder_ids=&team_name=
    def team_up
      authorize(Founder, policy_class: Schools::FounderPolicy)
      form = Schools::Founders::TeamUpForm.new(Reform::OpenForm.new)

      response = if form.validate(params)
        form.save
        { error: nil }
      else
        { error: form.errors.full_messages.join(', ') }
      end

      render json: response
    end

    # PATCH /school/students/:id
    def update
      student = authorize(scope.find(params[:id]), policy_class: Schools::FounderPolicy)
      @course = student.course

      form = Schools::Founders::EditForm.new(student)

      response = if form.validate(params[:founder].merge(tags: params[:tags], access_ends_at: params[:access_ends_at], coach_ids: params[:coach_ids]))
        form.save
        { error: nil }
      else
        { error: form.errors.full_messages.join(', ') }
      end

      render json: response
    end

    private

    def scope
      policy_scope(Founder, policy_scope_class: Schools::FounderPolicy::Scope)
    end
  end
end

app/views/schools/admins.html.erb
<% content_for(:head) do %>
  <title><%= current_school.name %> | Admins</title>
  <%= stylesheet_pack_tag 'SchoolAdminsPack', media: 'all' %>
<% end %>

<% content_for(:tail) do %>
  <%= javascript_pack_tag 'SchoolAdminsPack', 'data-turbolinks-track': 'reload', nonce: true %>
<% end %>

<script type="application/json" id="school-admins-data">
  <%= Schools::AdminsPresenter.new(self, current_school).props_to_json.html_safe %>
</script>

<div id="school-admins" class="flex flex-1 h-screen"></div>

app/views/schools/customize.html.erb
<% content_for(:head) do %>
  <title><%= current_school.name %> | Customization</title>
  <%= stylesheet_pack_tag 'SchoolsCustomizePack', media: 'all' %>
<% end %>

<% content_for(:tail) do %>
  <%= javascript_pack_tag 'SchoolsCustomizePack', nonce: true %>
<% end %>

<% presenter = Schools::CustomizePresenter.new(self) %>

<script type="application/json" id="school-customize-data">
  <%= presenter.json_props.html_safe %>
</script>

<div id="school-customize" class="w-full overflow-y-auto"></div>

app/views/schools/show.html.erb
<% content_for(:head) do %>
  <title><%= current_school.name %> | Overview</title>
  <%= stylesheet_pack_tag 'schools/show', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<% @presenter = Schools::ShowPresenter.new(self) %>
<div class="flex-1 flex flex-col bg-gray-200 overflow-y-auto">
  <div class="w-full p-6">
    <div class="max-w-3xl mx-auto relative rounded border overflow-hidden rounded-lg shadow-lg mx-3">
      <div class="bg-gradient-to-r from-secondary-500 to-secondary-600 bg-cover h-24 p-5">

      </div>
      <div class="flex px-5 pb-5 bg-white justify-between">
        <div class="flex">
          <div class="school-overview__logo-container flex items-center bg-white p-3 border rounded-lg -mt-16 overflow-hidden">
            <%= image_tag(@presenter.school_logo_path, alt: current_school.name) %>
          </div>
          <div class="school-overview__school-name pl-3 p-3">
            <span class="uppercase text-sm">School</span>
            <h2 class=""><%= @presenter.school_details[:name] %></h2>
          </div>
        </div>
        <div class="flex rounded-lg border mt-2">
          <div class="w-1/2 border-r">
            <div data-t="school students" class="p-3">
              <p>Students</p>
              <p><%= @presenter.school_details[:students_count] %></p>
            </div>
          </div>
          <div class="w-1/2">
            <div data-t="school coaches" class="p-3">
              <p>Coaches</p>
              <p><%= @presenter.school_details[:coaches_count] %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="w-full px-6">
    <div class="max-w-3xl w-full mx-auto my-8">
      <h2 class="font-semibold mb-4 pb-2 border-b">Courses</h2>
      <div class="flex flex-wrap items-stretch w-full school-overview__course-list">
        <% @presenter.course_details.each_with_index do |course, index| %>
          <div data-t="<%= course[:name] %> details" class="w-1/2 mb-4">
            <a class="block border rounded-lg bg-white shadow h-full cursor-pointer hover:border-primary-500 text-black" href=<%= school_course_students_path(course[:id]) %>>
              <div class="flex items-end justify-between border-b p-4 pt-6">
                <h3 class="font-bold text-xl"><%= course[:name] %></h3>
                <p class="text-sm"><%= course[:levels_count] %> <%= I18n.t("shared.level").pluralize(course[:levels_count]) %></p>
              </div>
              <div class="school-overview__course-list-card-count relative flex items-end bg-gray-200 justify-between border-b">
                <div data-t="<%= course[:name] %> students" class="w-1/2">
                  <div class="p-4">
                    <p>Students</p>
                    <p><%= course[:students_count] %></p>
                  </div>
                </div>
                <div data-t="<%= course[:name] %> coaches" class="w-1/2">
                  <div class="p-4">
                    <p>Coaches</p>
                    <p><%= course[:coaches_count] %></p>
                  </div>
                </div>
              </div>
              <div class="flex items-end p-4 text-xs items-center">
                <% if course[:submissions_count] == 0 %>
                  <i class="fas fa-inbox mr-2 text-2xl text-gray-600 bg-gray-200 p-1 rounded"></i>
                  <div class="text-gray-600">No student submissions yet!</div>
                <% elsif course[:submissions_count] == course[:evaluated_submissions_count] %>
                  <i class="fas fa-check mr-2 text-2xl text-green-600 bg-green-200 p-1 rounded"></i>
                  <div class="text-green-600">
                    <%= course[:evaluated_submissions_count] %>/<%= course[:submissions_count] %> submissions reviewed.
                  </div>
                <% else %>
                  <i class="fas fa-check mr-2 text-xl text-orange-600 bg-orange-200 p-1 rounded"></i>
                  <div class="text-orange-600">
                    <%= course[:evaluated_submissions_count] %>/<%= course[:submissions_count] %> submissions reviewed.
                  </div>
                <% end %>
              </div>
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>