config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  post '/graphql', to: 'graphql#execute'

  devise_for :users, only: %i[sessions omniauth_callbacks], controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/send_login_email', controller: 'users/sessions', action: 'send_login_email', as: 'user_send_login_email'
    post 'users/send_reset_password_email', controller: 'users/sessions', action: 'send_reset_password_email', as: 'user_send_reset_password_email'
    get 'users/token', controller: 'users/sessions', action: 'token', as: 'user_token'
    get 'users/reset_password', controller: 'users/sessions', action: 'reset_password', as: 'reset_password'
    post 'users/update_password', controller: 'users/sessions', action: 'update_password', as: 'update_password'

    if Rails.env.development?
      get 'users/auth/developer', controller: 'users/omniauth_callbacks', action: 'passthru', as: 'user_developer_omniauth_authorize'
      post 'users/auth/developer/callback', controller: 'users/omniauth_callbacks', action: 'developer'
    end
  end

  get 'users/delete_account', controller: 'users', action: 'delete_account', as: 'delete_account'

  post 'users/email_bounce', controller: 'users/postmark_webhook', action: 'email_bounce'

  authenticate :user, ->(u) { AdminUser.where(email: u.email).present? } do
    mount Delayed::Web::Engine, at: '/jobs'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resource :applicants, only: [] do
    get '/:token', action: 'enroll' # TODO: Legacy route - remove after a few weeks.
    get '/:token/enroll', action: 'enroll', as: 'enroll'
  end

  resources :notifications, only: %i[show]

  resource :school, only: %i[show update] do
    get 'customize'
    get 'admins'
    post 'images'
  end

  namespace :school, module: 'schools' do
    resources :faculty, only: %i[create update destroy], as: 'coaches', path: 'coaches' do
      collection do
        get '/', action: 'school_index'
      end
    end

    resources :targets, only: [] do
      resource :content_block, only: %i[create]
    end

    resources :courses, only: %i[index show new] do
      member do
        get 'details'
        get 'images', action: :details
        get 'actions', action: :details
        get 'curriculum'
        get 'exports'
        get 'authors'
        get 'certificates'
        post 'certificates', action: 'create_certificate'
        post 'bulk_import_students'
        get 'evaluation_criteria'
        post 'attach_images'
      end

      resources :authors, only: %w[show new]

      resources :targets, only: [] do
        member do
          get 'content'
          get 'details'
          get 'versions'
        end
      end

      resources :levels, only: %i[create]

      resources :faculty, as: 'coaches', path: 'coaches', only: [] do
        collection do
          get '/', action: 'course_index'
        end
      end

      post 'mark_teams_active'
      get 'students'
      get 'inactive_students'
      post 'delete_coach_enrollment'
      post 'update_coach_enrollments'
    end

    resources :founders, as: 'students', path: 'students', except: %i[index] do
      collection do
        post 'team_up'
      end
    end

    resources :levels, only: %i[update] do
      resources :target_groups, only: %i[create]
    end

    resources :target_groups, only: %i[update]

    resources :communities, only: %i[index]
  end

  resources :communities, only: %i[show] do
    member do
      get 'new_topic'
      get ':name', action: 'show'
    end
  end

  get 'topics/:id(/:title)', controller: 'topics', action: 'show', as: 'topic'

  get 'posts/:id/versions', controller: 'posts', action: 'versions', as: 'post_version'

  get 'dashboard', controller: 'users', action: 'dashboard', as: 'dashboard'

  resource :user, only: %i[edit] do
    post 'upload_avatar'
  end

  resources :timeline_event_files, only: %i[create] do
    member do
      get 'download'
    end
  end

  resources :faculty, only: %i[] do
    collection do
      get 'filter/:active_tab', to: 'faculty#index'
      get 'weekly_slots/:token', to: 'faculty#weekly_slots', as: 'weekly_slots'
      post 'save_weekly_slots/:token', to: 'faculty#save_weekly_slots', as: 'save_weekly_slots'
      delete 'weekly_slots/:token', to: 'faculty#mark_unavailable', as: 'mark_unavailable'
      get 'slots_saved/:token', to: 'faculty#slots_saved', as: 'slots_saved'
    end
  end

  scope 'coaches', controller: 'faculty' do
    get '/', action: 'index', as: 'coaches_index'
    get '/:id(/:slug)', action: 'show', as: 'coach'
    get '/filter/:active_tab', action: 'index'
  end

  scope 'connect_request', controller: 'connect_request', as: 'connect_request' do
    get ':id/feedback/from_team/:token', action: 'feedback_from_team', as: 'feedback_from_team'
    get ':id/feedback/from_faculty/:token', action: 'feedback_from_faculty', as: 'feedback_from_faculty'
    get ':id/join_session(/:token)', action: 'join_session', as: 'join_session'
    patch ':id/feedback/comment/:token', action: 'comment_submit', as: 'comment_submit'
  end

  # Founder show
  scope 'students', controller: 'founders' do
    get '/:id/report', action: 'report', as: 'student_report'
  end

  get 'styleguide', to: 'home#styleguide', constraints: DevelopmentConstraint.new

  get 'manifest', to: 'home#manifest'
  get 'offline', to: 'home#offline'
  root 'home#index'

  # TODO: Remove this backwards-compatibility path after Jan 2021.
  get 'agreements/terms-of-use', to: redirect('/agreements/terms-and-conditions')

  get 'agreements/:agreement_type', as: 'agreement', controller: 'home', action: 'agreement'

  resources :targets, only: %i[show] do
    member do
      get 'details_v2'
      get ':slug', action: 'show'
    end
  end

  resources :timeline_events, only: %i[show], path: 'submissions' do
    member do
      get 'review', action: 'review'
    end
  end

  resources :courses, only: %i[show] do
    member do
      get 'review', action: 'review'
      get 'students', action: 'students'
      get 'leaderboard', action: 'leaderboard'
      get 'curriculum', action: 'curriculum'
      get 'report', action: 'report'
      get 'apply', action: 'apply'
      get '/(:name)', action: 'show'
    end
  end

  resources :markdown_attachments, only: %i[create] do
    member do
      get '/:token', action: 'download', as: 'download'
    end
  end

  get '/c/:serial_number', to: 'issued_certificates#verify', as: :issued_certificate
  get '/help/:document', to: 'help#show'
  get '/oauth/:provider', to: 'home#oauth', as: 'oauth', constraints: SsoConstraint.new
  get '/oauth_error', to: 'home#oauth_error', as: 'oauth_error'

  # Allow developers to simulate the error pages.
  get '/errors/:error_type', to: 'errors#simulate', constraints: DevelopmentConstraint.new

  get '/service-worker.js', to: 'home#service_worker'
  get '/favicon.ico', to: 'home#favicon'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, except: %i[show apply curriculum]
  before_action :preview_or_authenticate, only: %i[curriculum]

  # GET /courses/:id/curriculum
  def curriculum
    @presenter = Courses::CurriculumPresenter.new(view_context, @course)
    render layout: 'student_course'
  end

  # GET /courses/:id/leaderboard?weeks_before=
  def leaderboard
    @course = authorize(find_course)
    @on = params[:on]
    render layout: 'student_course'
  end

  # GET /courses/:id/apply
  def apply
    @course = authorize(find_course)
    save_tag
    render layout: 'tailwind'
  end

  # GET /courses/:id/(:slug)
  def show
    @course = authorize(find_course)
    render layout: 'student'
  end

  # GET /courses/:id/review
  def review
    @course = authorize(find_course)
    render layout: 'student_course'
  end

  # GET /courses/:id/students
  def students
    @course = authorize(find_course)
    render layout: 'student_course'
  end

  # GET /courses/:id/report
  def report
    @course = authorize(find_course)
    render layout: 'student_course'
  end

  private

  def preview_or_authenticate
    course = find_course

    authenticate_user! unless course.public_preview?

    @course = authorize(course)
  end

  def find_course
    policy_scope(Course).find(params[:id])
  end

  def save_tag
    return if params[:tag].blank?

    if params[:tag].in?(current_school.founder_tag_list)
      session[:applicant_tag] = params[:tag]
    end
  end
end

app/controllers/schools/courses_controller.rb
module Schools
  class CoursesController < SchoolsController
    include CamelizeKeys
    include StringifyIds

    layout 'school'

    # GET /school/courses
    def index
      authorize(current_school, policy_class: Schools::CoursePolicy)
    end

    # GET /school/course/new
    def new
      index
      render 'index'
    end

    # GET /school/course/id/
    def show
      @course = authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
      redirect_to details_school_course_path
    end

    # GET /school/course/id/details
    def details
      @course = authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
      render 'index'
    end

    # POST /courses/id/attach_images
    def attach_images
      course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
      @form = Schools::Courses::UpdateImagesForm.new(course)

      if @form.validate(params)
        @form.save
        render json: {
          thumbnail_url: course.thumbnail_url,
          cover_url: course.cover_url,
          error: nil
        }
      else
        render json: {
          thumbnail_url: nil,
          cover_url: nil,
          error: @form.errors.full_messages.join(', ')
        }
      end
    end

    # GET /courses/:id/curriculum
    def curriculum
      course =
        scope
          .where(id: params[:id])
          .includes(:evaluation_criteria, :levels, :target_groups, :targets)
          .first
      @course = authorize(course, policy_class: Schools::CoursePolicy)
    end

    # POST /school/courses/:course_id/delete_coach_enrollment
    def delete_coach_enrollment
      coach = current_school.faculty.find(params[:coach_id])
      course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )

      ::Courses::UnassignReviewerService.new(course).unassign(coach)

      render json: { coach_id: coach.id.to_s, error: nil }
    end

    def update_coach_enrollments
      course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )
      coaches =
        current_school.faculty.where(id: params[:coach_ids]).includes(:school)

      coaches.each do |coach|
        ::Courses::AssignReviewerService.new(course, notify: true).assign(coach)
      end

      course_coaches =
        coaches.map do |coach|
          {
            id: coach.id.to_s,
            name: coach.name,
            title: coach.title,
            email: coach.email,
            avatarUrl: coach.user.avatar_url(variant: :thumb)
          }
        end

      render json: { course_coaches: course_coaches, error: nil }
    end

    # GET /school/courses/:course_id/students
    def students
      @course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )
    end

    def inactive_students
      @course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )

      inactive_teams =
        if params[:search].present?
          ::Courses::InactiveTeamsSearchService
            .new(@course)
            .find_teams(params[:search].to_s)
        else
          Startup.joins(:course).inactive.where(courses: { id: @course }).to_a
        end

      @teams =
        Kaminari.paginate_array(inactive_teams).page(params[:page]).per(20)
    end

    # POST /school/courses/:course_id/mark_teams_active?team_ids[]=
    def mark_teams_active
      course =
        authorize(
          scope.find(params[:course_id]),
          policy_class: Schools::CoursePolicy
        )

      Startup.transaction do
        course
          .startups
          .where(id: params[:team_ids])
          .each do |startup|
          startup.update!(access_ends_at: nil, dropped_out_at: nil)
        end

        render json: {
          message: 'Teams marked active successfully!',
          error: nil
        }
      end
    end

    # GET /school/courses/:id/exports
    def exports
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    # GET /school/courses/:id/authors
    def authors
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    # GET /school/courses/:id/certificates
    def certificates
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    # POST /school/courses/:id/certificates
    def create_certificate
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)

      form = ::Courses::CreateCertificateForm.new(@course)

      props =
        if form.validate(params)
          scope = Certificate.where(id: form.save.id)
          ActiveRecord::Precounter.new(scope).precount(:issued_certificates)

          {
            error: nil,
            certificate:
              Schools::Courses::CertificatesPresenter.certificate_details(
                scope.first
              )
          }
        else
          { error: form.errors.full_messages.join(', ') }
        end

      render json: camelize_keys(stringify_ids(props))
    end


    # POST /school/courses/:id/bulk_import_students
    def bulk_import_students
      @course = authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)

      form = ::Courses::BulkImportStudentsForm.new(@course)
      form.current_user = current_user

      props = if form.validate(params)
        form.save
        {
          success: true,
        }
      else
        { error: form.errors.full_messages.join(", ") }
      end

      render json: camelize_keys(stringify_ids(props))
    end

    # GET /school/courses/:id/evaluation_criteria
    def evaluation_criteria
      @course =
        authorize(scope.find(params[:id]), policy_class: Schools::CoursePolicy)
    end

    private

    def scope
      @scope ||=
        policy_scope(Course, policy_scope_class: Schools::CoursePolicy::Scope)
    end
  end
end

app/views/courses/_topper_avatar.html.erb
<div class="leaderboard__winner-avatar">
  <% if student.avatar.attached? %>
    <%= image_tag (student.avatar_variant(:thumb)), class: 'w-full object-contain' %>
  <% else %>
    <%= image_tag (student.initials_avatar), class: 'w-full object-contain' %>
  <% end %>
</div>

app/views/courses/apply.html.erb
<% presenter = Courses::ApplyPresenter.new(self, @course) %>

<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
  <%= stylesheet_pack_tag 'CoursesApplyPack', media: 'all' %>
<% end %>

<% content_for(:tail) do %>
  <%= javascript_pack_tag 'CoursesApplyPack', nonce: true %>
<% end %>

<script id="react-root-data" type="application/json"><%= presenter.props_to_json.html_safe %></script>
<div id="react-root"></div>

app/views/courses/curriculum.html.erb
<% content_for(:head) do %>
  <title><%= @presenter.page_title %></title>
  <%= stylesheet_pack_tag 'CoursesCurriculumPack', media: 'all' %>
<% end %>

<% content_for(:tail) do %>
  <%= javascript_pack_tag 'CoursesCurriculumPack', nonce: true %>
<% end %>

<% content_for(:inner_wrapper) do %>
  <script id="react-root-data" type="application/json"><%= @presenter.props_to_json.html_safe %></script>
  <div id="react-root"></div>
<% end %>

app/views/courses/leaderboard.html.erb
<% presenter = Courses::LeaderboardPresenter.new(self, @course, @on) %>

<% content_for(:head) do %>
  <title>Leaderboard | <%= presenter.school_name %></title>
  <%= stylesheet_pack_tag 'courses/leaderboard', 'data-turbolinks-track': 'reload' %>
<% end %>
<% content_for(:inner_wrapper) do %>
  <div class="bg-gray-100 pt-11 pb-8 -mt-7">
    <div class="max-w-3xl mx-auto">
      <div class="text-center mx-3">
        <p class="inline-block bg-primary-100 text-primary-900 border border-primary-500 text-xs mx-auto text-center px-4 py-2 rounded-lg">
          This leaderboard shows students <strong>who have improved the most</strong> compared to the previous
          leaderboard.
        </p>
      </div>
      <div class="w-full md:px-4 text-center mt-4">
        <div class="leaderboard__header-container">
          <div class="w-5/6 lg:w-4/6 mx-auto">
            <div>
              <% if presenter.students.any? %>
                <div class="flex justify-center">
                  <% if presenter.toppers.count > 3 %>
                    <% presenter.toppers[0..1].each do |student| %>
                      <%= render 'topper_avatar', student: student %>
                    <% end %>
                  <% else %>
                    <% presenter.toppers.each do |student| %>
                      <%= render 'topper_avatar', student: student %>
                    <% end %>
                  <% end %>

                  <% if presenter.toppers.count > 3 %>
                    <div class="leaderboard__winner-avatar flex items-center justify-center font-bold bg-gray-300">
                      +<%= presenter.toppers.count - 2 %>
                    </div>
                  <% end %>
                </div>

                <h4 class="leaderboard__winner-title pb-3 mt-3 font-normal leading-snug text-primary-900"><%= presenter.heading %></h4>

                <div class="leaderboard__students-count-container bg-gray-100 flex mx-auto overflow-hidden border rounded-lg justify-center">
                  <div class="w-1/2 px-2 pt-2 pb-1" data-t='active students count'>
                    <p class="text-xs">Active Students</p>
                    <span class="text-xl font-semibold"><%= presenter.students.count %></span>
                  </div>
                  <div class="w-1/2 px-2 pt-2 pb-1" data-t='inactive students count'>
                    <p class="text-xs">Inactive Students</p>
                    <span class="text-xl font-semibold"><%= presenter.inactive_students_count %></span>
                  </div>
                </div>
              <% end %>
              <div class="flex items-center justify-center max-w-xs mx-auto h-10 mb-3 mt-5">
                <% if presenter.previous_page? %>
                  <a class="text-primary bg-white hover:bg-primary-100 hover:text-primary-600 hover:border-primary-300 hover:shadow-md focus:bg-primary-600 focus:text-white focus:shadow-inner bg-white px-4 py-2 h-full flex items-center justify-center border border-gray-400 rounded-lg" href="<%= presenter.previous_page_link %>">
                    <i class="fas fa-angle-left text-lg"></i>
                  </a>
                <% end %>
                <span class="bg-white px-6 py-2 text-sm flex items-center flex-shrink-0 h-full mx-1 md:mx-2 font-semibold border border-gray-400 rounded-lg">
                  <%= presenter.start_date %> to <%= presenter.end_date %>
                </span>
                <% if presenter.next_page? %>
                  <a class="text-primary bg-white hover:bg-primary-100 hover:text-primary-600 hover:border-primary-300 hover:shadow-md focus:bg-primary-600 focus:text-white focus:shadow-inner px-4 py-2 h-full flex items-center justify-center border border-gray-400 rounded-lg" href="<%= presenter.next_page_link %>">
                    <i class="fas fa-angle-right text-lg"></i>
                  </a>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if presenter.students.empty? %>
        <div class="leaderboard__inactive-startup-message text-center bg-white border shadow rounded-lg px-3 md:px-5 mx-3 py-8 my-4">
          <h4 class="font-semibold">
            The leaderboard doesn&rsquo;t have any entries for this period.
          </h4>
        </div>
      <% else %>
        <div class="leaderboard__table-container w-full bg-white border-t border-b md:border border-gray-400 scrolling-touch shadow-lg overflow-x-auto lg:overflow-hidden lg:rounded-lg">
          <table class="w-full mb-2 border-collapse relative">
            <thead class="bg-gray-200">
            <tr>
              <th class="py-3 px-3 bg-grey-100 font-bold uppercase text-sm border-b">Rank</th>
              <th class="py-3 px-3 bg-grey-100 font-bold uppercase text-sm border-b">Change</th>
              <th class="py-3 px-3 bg-grey-100 font-bold uppercase text-sm border-b text-left">Student</th>
              <th class="py-3 px-3 bg-grey-100 font-bold uppercase text-sm border-b">Level</th>
              <th class="py-3 px-3 bg-grey-100 font-bold uppercase text-sm border-b">Score</th>
            </tr>
            </thead>

            <tbody>
            <% presenter.students.each do |student| %>
              <tr class="<%= student.current_student? ? 'leaderboard__current-student-row shadow-lg' : 'leaderboard__student-row' %>">
                <td class="py-3 px-3 border-b font-bold text-center">
                  <span><%= student.rank %></span>
                </td>

                <td class="py-3 px-3 border-b font-semibold text-sm text-center">
                  <% if student.delta.blank? %>
                    <span class="leaderboard__rank-change-new">New</span>
                  <% else %>
                    <span class="leaderboard__rank-change-icon inline-block mr-1">
                      <%= presenter.rank_change_icon(student.delta) %>
                    </span>
                  <% end %>

                  <span class="leaderboard__rank-delta font-semibold"><%= presenter.format_delta(student.delta) %></span>
                </td>

                <td class="py-3 px-3 border-b text-left text-sm">
                  <span class="font-semibold inline-block leading-tight"><%= student.name %></span>
                  <span class="leaderboard__student-affiliation block text-xs text-gray-700 leading-tight"> <%= student.user.affiliation %></span>
                </td>
                <td class="py-3 px-3 border-b text-center font-semibold text-sm"><%= student.level_number %></td>
                <td class="py-3 px-3 border-b text-center font-semibold text-sm"><%= student.score %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/courses/report.html.erb
<% presenter = Courses::ReportPresenter.new(self, @course) %>

<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
  <%= stylesheet_pack_tag 'CoursesReportPack', media: 'all' %>
<% end %>

<% content_for(:tail) do %>
  <%= javascript_pack_tag 'CoursesReportPack', nonce: true %>
<% end %>


<% content_for(:inner_wrapper) do %>
  <script id="course-student-report__props" type="application/json"><%= presenter.props_to_json.html_safe %></script>
  <div id="react-root"></div>
<% end %>

app/views/courses/review.html.erb
<% presenter = Courses::ReviewPresenter.new(self, @course) %>

<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
  <%= stylesheet_pack_tag 'CoursesReviewPack', media: 'all' %>
<% end %>

<% content_for(:tail) do %>
  <%= javascript_pack_tag 'CoursesReviewPack', nonce: true %>
<% end %>

<% content_for(:inner_wrapper) do %>
  <div id="react-root" data-json-props="<%= presenter.props_to_json %>"></div>
<% end %>

app/views/courses/show.html.erb
<% presenter = Courses::ShowPresenter.new(self, @course) %>

<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
  <%= stylesheet_pack_tag 'courses/shared', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'courses/show', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'shared/markdownBlockCSS', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="pb-8 bg-gray-100 ">
  <div class="relative bg-primary-900">
    <div class="relative pb-1/2 md:pb-1/4 2xl:pb-1/5">
      <% if presenter.cover_image.present? %>
        <img
          class="absolute h-full w-full object-cover"
          src="<%= presenter.cover_image %>"
        />
      <% else %>
        <div
          class="course-show__cover-default absolute h-full w-full svg-bg-pattern-1"
        ></div>
      <% end %>
    </div>
  </div>
  <div class="px-3">
    <div
      class="course-show__header-cta-container bg-white border-transparent lg:max-w-3xl mx-auto shadow rounded-lg -mt-5 md:-mt-7 z-10 relative pt-4 pb-5 md:py-8"
    >
      <div class="flex md:flex-row flex-col">
        <div class="w-full md:w-2/3 pl-4 md:pl-8 ">
          <h1 class="font-bold leading-snug">
            <%= @course.name %>
          </h1>
          <div class="mt-2">
            <%= @course.description %>
          </div>
        </div>
        <% if @course.public_signup %>
          <div
            class="w-full md:w-1/3 flex justify-center items-center mt-4 md:mt-0 px-4 md:px-8"
          >
            <a
              href="<%= apply_course_path(@course) %>"
              class="btn btn-success btn-large w-full"
            >
              Apply Now
            </a>
          </div>
        <% end %>
        <% if @course.public_preview? %>
          <div
            class="w-full md:w-1/3 flex justify-center items-center mt-4 md:mt-0 px-4 md:px-8"
          >
            <a
              href="<%= curriculum_course_path(@course) %>"
              class="btn btn-primary btn-large w-full"
            >
              <%= presenter.user_is_student? ? t('courses.show.continue_course') : t('courses.show.preview_course') %>
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="mt-4">
    <% if presenter.show_about? %>
      <div class="max-w-3xl mx-auto relative z-10 pb-8">
        <div class="px-4 md:px-8 markdown-block markdown-block__permissive">
          <%= sanitize(presenter.about) %>
        </div>
        <% if @course.public_signup %>
          <div
            class="course-show__footer-cta-container bg-white py-12 px-4 text-center mt-8 border-transparent shadow rounded-lg md:mx-8 mx-4"
          >
            <h2 class="text-3xl leading-tight">
              <span class="font-normal"> Enroll to </span>
              <span class="block font-bold">
                <%= @course.name %>
              </span>
            </h2>
            <a
              href="<%= apply_course_path(@course) %>"
              class="btn btn-large btn-success w-full sm:w-auto course-show__footer-cta-button shadow mt-3"
              >Apply Now</a
            >
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/students.html.erb
<% presenter = Courses::StudentsPresenter.new(self, @course) %>
<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
  <%= stylesheet_pack_tag 'CoursesStudentsPack', media: 'all' %>
<% end %>

<% content_for(:tail) do %>
  <%= javascript_pack_tag 'CoursesStudentsPack', nonce: true %>
<% end %>

<% content_for(:inner_wrapper) do %>
  <script id="school-course-students__props" type="application/json"><%= presenter.props_to_json.html_safe %></script>
  <div id="react-root"></div>
<% end %>